version: "3.7"

x-default-volumes: &default-volumes
  volumes:
    #- ./:/app
    #- node-module:/app/node_module
    - ../galaxycatalog-volumes/bucket:/bucket

services:
  flask:
    build: .
    #target: flask-dev
    image: galaxycatalog-flask-dev-image
    container_name: galaxycatalog-flask-dev-container
    environment:
      - FLASK_APP=app
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=galaxycatalog
    ports:
      - 5000:5000
    volumes:
      - ./:/app
      - ../galaxycatalog-volumes/bucket:/bucket
    #command: /srv/start
  postgres:
    image: postgres:14-alpine
    container_name: galaxycatalog-postgres-dev-container
    restart: always
    environment:
      - POSTGRES_PASSWORD=example
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ../galaxycatalog-volumes/pgdata:/var/lib/postgresql/data/pgdata
      - ../galaxycatalog-volumes/bucket:/bucket
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080