"""init2

Revision ID: 549663639876
Revises: e9072a497338
Create Date: 2021-11-19 03:56:01.941289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549663639876'
down_revision = 'e9072a497338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
