"""field_numbers

Revision ID: e294070cf0a6
Revises: 426c79e21581
Create Date: 2021-11-19 07:58:14.023713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e294070cf0a6'
down_revision = '426c79e21581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gathering_person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gathering_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gathering_id'], ['gathering.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('collector_number', sa.String(length=500), nullable=True),
    sa.Column('collector_id', sa.Integer(), nullable=True),
    sa.Column('collector_name', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['collector_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('gather_person_other')
    op.drop_column('unit', 'field_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('field_number', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_table('gather_person_other',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('gathering_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['gathering_id'], ['gathering.id'], name='gather_person_other_gathering_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name='gather_person_other_person_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='gather_person_other_pkey')
    )
    op.drop_table('field_number')
    op.drop_table('gathering_person')
    # ### end Alembic commands ###
